const path = {
  LAYOUT: "/",
  INVALID: "*",
  HOME: "",
  LOGIN: "login",
  ADMIN: "admin",
  SUPER_ADMIN: "adminsp",
  MEMBER: "member",
  MANAGER: "manager",
  BILL: "bill",

  PHONGTRO: "cho-thue-tro",
  CANHO: "cho-thue-nha-can-ho",
  TIMOGHEP: "tim-o-ghep",
  BLOG: "blog",
  GUIDE: "huong-dan",

  LIST: "danh-sach",
  DETAIL_POST: "chi-tiet-tin-dang",
  DETAIL_POST__PID__TITLE: "chi-tiet-tin-dang/:pid/:title/*",
  DASHBOARD: "dashboard",
  MANAGE_POST_ALL: "quan-ly-tat-ca-tin-dang",
  PERSONAL: "thong-tin-ca-nhan",
  MANAGE_USER: "quan-ly-thanh-vien",
  MANAGE_POST: "quan-ly-tin-dang",
  CREATE_POST: "tao-moi-tin-dang",
  FILTER: "tim-kiem",
  WISHLIST: "danh-sach-yeu-thich",
  VERIFY_PHONE: "xac-minh-so-dien-thoai",
  MANAGER_HOUSE: "house",
  MANAGER_ELECTRIC_WATER: "electric-water",
  MANAGER_SERVICE: "service",

  CHANGE_PHONE: "cập-nhat-so-dien-thoai",
  CHANGE_PASSWORD: "doi-mat-khau",
  TOP_PROVINCE__NAME: "tinh-thanh/:name",
  TOP_PROVINCE: "tinh-thanh",
  DEPOSIT: "nap-tien",
  PAYMENT_RESULT: "payment/status",
  MANAGE_DEPOSIT: "quan-ly-nap-tien",
  PRICING: "bang-gia-dich-vu",
  CREATE_PRICING: "tao-moi-bang-gia-dich-vu",
  MANAGE_PRICING: "quan-ly-bang-gia-dich-vu",
  MANAGER_PAYMENT: "payment",
  HISTORIES_PAYMENT: "lich-su-thanh-toan",
  MANAGE_REPORT: "bao-cao-vi-pham",
  MANAGE_PAYMENT: "quan-ly-thanh-toan",
}

export default path
